### ISSUE TITLE
Does not work with Renovate bot

### ISSUE THREAD

**Issue by kgnfth** [dogger/dogger.io#19]
When [Renovate](https://github.com/marketplace/renovate) sends a pull request pull-dog does nothing

it only works when i create a pull manually

**Comment by ffMathy** [comment]
Hi @kgnfth !

I see! Did you close the issue because you solved it?

**Comment by kgnfth** [comment]
@ffMathy No

**Comment by ffMathy** [comment]
@kgnfth can you link to a pull request where it happened?

**Comment by kgnfth** [comment]
> @kgnfth can you link to a pull request where it happened?

its a private repo, but i will create a demo repo right now and get back to you

**Comment by kgnfth** [comment]
@ffMathy here https://github.com/kgnfth/dogger-test/pull/1

**Comment by ffMathy** [comment]
@kgnfth it does seem there are some difficulties with the service right now. I'll check back soon!

**Comment by kgnfth** [comment]
> @kgnfth it does seem there are some difficulties with the service right now. I'll fix it and check back soon!

Yes i get Gateway time-out when trying to authorize `https://app.dogger.io/pull-dog/install/github?code=redacted&installation_id=16215961&setup_action=install`

**Comment by ffMathy** [comment]
It should be back online now.

Can you try again? :pray:

It still doesn't work for me in your repo, but are you sure that it has been installed there? Also, does it work for pull requests that are not created by Renovate?

**Comment by kgnfth** [comment]
> It should be back online now.
> 
> Can you try again? 🙏
> 
> It still doesn't work for me in your repo, but are you sure that it has been installed there? Also, does it work for pull requests that are not created by Renovate?

Hey, i tried reinstalling the app but it your site `app.dogger.io` gives me `Gateway time-out` error
but it appears its installed in the repo

![image](https://user-images.githubusercontent.com/73314940/114928641-1d7a3100-9e33-11eb-9094-124207694821.png)

**Comment by ffMathy** [comment]
Yes indeed - very perculiar. Something is causing the service to go down. I think it somehow has something to do with your user.

I'll investigate. Pull Dog has 98% code coverage, with both integration and unit tests. It has been running for several users over a course of almost a year without issues.

It's strange that this starts happening now.

Oh well, that's the life of any developer I guess.

I'll get back to you! 😄

**Comment by ffMathy** [comment]
Hmmm, it seems that for your user, for some reason, GitHub gave Pull Dog a bad auth code when redirecting.

![image](https://user-images.githubusercontent.com/2824010/114936172-59fe5a80-9e3c-11eb-95e2-3ed348a32e4c.png)

In addition, it seems that the issues with load of the whole server (with the gateway time-out) happened when you tried to install the app on to your account.

![image](https://user-images.githubusercontent.com/2824010/114936384-a9448b00-9e3c-11eb-99fb-9b6638405979.png)

I'll investigate further!

**Comment by kgnfth** [comment]
@ffMathy yes it happens when its trying to authorize or something..

going to bed now soo tired 😅

**Comment by ffMathy** [comment]
That's okay - no rush ^^

And thanks once again for the patience.

Do you have a lot of repositories in your account? (public and private)

**Comment by ffMathy** [comment]
Under "Installed GitHub Apps" in the GitHub settings (the screenshot you showed me), can you click "Configure", and then click "Uninstall" for Pull Dog?

And then try to install it again?

**Comment by ffMathy** [comment]
I applied some fixes which may solve the problem, if you follow the steps above.

Here's the code changes if you'd like to see them: https://github.com/dogger/app.dogger.io/pull/1060

**Comment by kgnfth** [comment]
> Under "Installed GitHub Apps" in the GitHub settings (the screenshot you showed me), can you click "Configure", and then click "Uninstall" for Pull Dog?
> 
> And then try to install it again?

Hey i just uninstalled and revoked oauth and reinstalled pull-dog, but i keep getting Error 504 when authorizing




https://user-images.githubusercontent.com/73314940/115020153-77720980-9eba-11eb-9ffb-cd0d449c4a93.mp4



I really appreciate your hard work

**Comment by ffMathy** [comment]
No, thank YOU for your hard work and patience!

Hmmm that's indeed strange. How many private repositories do you have?

**Comment by kgnfth** [comment]
> No, thank YOU for your hard work and patience!
> 
> Hmmm that's indeed strange. How many private repositories do you have?

Only two

**Comment by kgnfth** [comment]
@ffMathy pull-dog is working https://github.com/kgnfth/dogger-test/pull/6

**Comment by ffMathy** [comment]
Great! Then my latest fixes worked. Thanks for the report! 🙏✌️
